name: PunishSystem32
version: '1.0.0'
main: com.x32pc.github.PunishSystem32
api-version: '1.20'
commands:
  history:
    usage: /<command>
    description: History command
  unmute:
    usage: /<command>
    description: Unmute command
  unblacklist:
    usage: /<command>
    description: Unblacklist command
  blacklist:
    usage: /<command>
    description: Blacklist command
  tempban:
    usage: /<command>
    description: Tempban command
  unban:
    usage: /<command>
    description: Unban player
  ban:
    usage: /<command>
    description: Ban player
  tempmute:
    usage: /<command>
    description: Tempmute command
  mute:
    usage: /<command>
    description: Mute command
  kick:
    usage: /<command>
    description: Kick command
